export const databaseInterviewQuestions = {
    mysql: {
        basic: [
            "What is MySQL?",
            "What is a database?",
            "What is a table in MySQL?",
            "What is a row and a column?",
            "What is a primary key?",
            "What is a foreign key?",
            "What is the difference between CHAR and VARCHAR?",
            "What is the difference between INT and BIGINT?",
            "What is NULL?",
            "What is the AUTO_INCREMENT attribute?",
            "What is a UNIQUE constraint?",
            "What is a DEFAULT constraint?",
            "What is the difference between DELETE, DROP, and TRUNCATE?",
            "What is the SELECT statement?",
            "How do you filter records using WHERE?",
            "What is the ORDER BY clause?",
            "What is the LIMIT clause?",
            "What is the LIKE operator?",
            "What is the IN operator?",
            "What is the BETWEEN operator?"
        ],

        intermediate: [
            "What is normalization?",
            "What are the different normal forms (1NF, 2NF, 3NF)?",
            "What are SQL joins?",
            "What is the difference between INNER JOIN and LEFT JOIN?",
            "What is the difference between LEFT JOIN and RIGHT JOIN?",
            "What is a SELF JOIN?",
            "What is a CROSS JOIN?",
            "What is GROUP BY?",
            "What is the HAVING clause?",
            "What is the difference between WHERE and HAVING?",
            "What are aggregate functions?",
            "What is COUNT()?",
            "What is SUM()?",
            "What is AVG()?",
            "What is MIN() and MAX()?",
            "What is an index?",
            "Why are indexes used?",
            "What are the advantages and disadvantages of indexes?",
            "What is a composite index?",
            "What is a view?"
        ],

        practical: [
            "Write a query to fetch all users.",
            "Write a query to fetch users older than 18.",
            "Write a query to sort users by name.",
            "Write a query to get the top 5 highest-paid employees.",
            "Write a query to count total users.",
            "Write a query using INNER JOIN.",
            "Write a query using LEFT JOIN.",
            "Write a query using GROUP BY.",
            "Write a query to find duplicate records.",
            "Write a query to find the second highest salary.",
            "Write a query to paginate results using LIMIT and OFFSET.",
            "Write a query to update user information.",
            "Write a query to delete a user.",
            "Design tables for a simple e-commerce application.",
            "Design tables for a blog application."
        ],
        MustKnow: [
            "Primary Key",
            "Foreign Key",
            "DELETE vs DROP vs TRUNCATE",
            "INNER JOIN vs LEFT JOIN",
            "WHERE vs HAVING",
            "GROUP BY",
            "Indexes",
            "Normalization",
            "COUNT, SUM, AVG",
            "Second Highest Salary Query"
        ],
    },

    mongodb: {
        basic: [
            "What is MongoDB?",
            "What is NoSQL?",
            "What is the difference between SQL and NoSQL?",
            "What is a collection?",
            "What is a document?",
            "What is BSON?",
            "What is the ObjectId?",
            "How do you insert a document?",
            "How do you find documents?",
            "What is findOne()?",
            "How do you update documents?",
            "How do you delete documents?",
            "What is the difference between deleteOne and deleteMany?",
            "What is projection in MongoDB?",
            "How do you sort documents?",
            "How do you limit documents?",
            "What is skip() used for?",
            "How does pagination work in MongoDB?",
            "What is MongoDB Compass?",
            "What is Mongoose?"
        ],

        intermediate: [
            "What is a schema in Mongoose?",
            "What is a model in Mongoose?",
            "What is the difference between a schema and a model?",
            "What are Mongoose validations?",
            "How do you create relationships in MongoDB?",
            "What is embedding?",
            "What is referencing?",
            "When should you use embedding vs referencing?",
            "What is populate() in Mongoose?",
            "How does populate() work?",
            "What are indexes in MongoDB?",
            "Why are indexes important?",
            "What is a unique index?",
            "What is aggregation in MongoDB?",
            "What is the $match stage?",
            "What is the $group stage?",
            "What is the $lookup stage?",
            "How do you count documents?",
            "How do you search documents efficiently?",
            "How do you optimize MongoDB queries?"
        ],

        practical: [
            "Create a User schema using Mongoose.",
            "Create a Product schema using Mongoose.",
            "Implement CRUD operations using Mongoose.",
            "Implement pagination in MongoDB.",
            "Implement search functionality.",
            "Use populate() to fetch related data.",
            "Create a one-to-many relationship.",
            "Create a many-to-many relationship.",
            "Write an aggregation pipeline using $match.",
            "Write an aggregation pipeline using $group.",
            "Write an aggregation pipeline using $lookup.",
            "Find duplicate documents.",
            "Create indexes for frequently searched fields.",
            "Design a blog database schema.",
            "Design an e-commerce database schema."
        ],

        MustKnow: [
            "SQL vs MongoDB",
            "Collection vs Document",
            "Schema vs Model",
            "Mongoose",
            "CRUD Operations",
            "Embedding vs Referencing",
            "populate()",
            "Indexes",
            "Aggregation",
            "Pagination"
        ],
    }
};