export const genAiInterviewQuestions = {
    basic: [
        "What is Generative AI?",
        "What is the difference between AI, ML, and Generative AI?",
        "What are Large Language Models (LLMs)?",
        "How does an LLM generate text?",
        "What are tokens in the context of LLMs?",
        "What is a context window?",
        "What is prompt engineering?",
        "What is temperature in LLMs and how does it affect output?",
        "What is top-p (nucleus sampling)?",
        "What is the difference between GPT and Gemini models?",
        "What is the Gemini API?",
        "What is OpenAI API?",
        "What is a system prompt?",
        "What is zero-shot prompting?",
        "What is few-shot prompting?",
        "What is chain-of-thought prompting?",
        "What is a transformer architecture?",
        "What are embeddings in AI?",
        "What is a vector database?",
        "What is semantic search?",
    ],

    intermediate: [
        "What is Retrieval-Augmented Generation (RAG)?",
        "How does RAG work step by step?",
        "What is fine-tuning and when should you use it?",
        "What is the difference between RAG and fine-tuning?",
        "What is LangChain and what problem does it solve?",
        "What are AI agents?",
        "What is tool/function calling in LLMs?",
        "What are hallucinations in AI and how do you minimize them?",
        "What is grounding in AI?",
        "What is RLHF (Reinforcement Learning from Human Feedback)?",
        "What are vector embeddings and how are they stored?",
        "What is cosine similarity in the context of embeddings?",
        "What is chunking in RAG pipelines?",
        "What is a prompt template?",
        "What are output parsers?",
        "What are the differences between chat models and completion models?",
        "What is streaming in LLM APIs?",
        "What is LlamaIndex?",
        "What is Pinecone/Weaviate/Chroma used for?",
        "What is the difference between open-source and closed-source LLMs?",
    ],

    advanced: [
        "How would you architect a production-ready RAG system?",
        "How do you evaluate the quality of LLM outputs?",
        "What are evaluation metrics for RAG (faithfulness, relevance, context recall)?",
        "How do you handle token limits in large documents?",
        "What is multi-modal AI?",
        "What is agentic AI and multi-agent orchestration?",
        "How do you implement streaming responses from the Gemini API in Next.js?",
        "What are guardrails in AI applications?",
        "How do you prevent prompt injection attacks?",
        "What is model distillation?",
    ],

    practical: [
        "Integrate the Gemini API into a Next.js app using Server Actions.",
        "Build a simple chatbot using the Gemini API.",
        "Implement streaming responses from an LLM in a React frontend.",
        "Build a document Q&A system using RAG.",
        "Implement a semantic search feature using embeddings.",
        "Use LangChain to build a multi-step AI pipeline.",
        "Implement tool/function calling with the Gemini API.",
        "Build a system prompt that enforces a specific output format.",
        "Implement chat history / conversation memory.",
        "Evaluate an AI response using a simple automated test.",
    ],

    MustKnow: [
        "RAG (Retrieval-Augmented Generation)",
        "Prompt Engineering (zero-shot, few-shot, chain-of-thought)",
        "Embeddings & Vector Databases",
        "Temperature & Top-p",
        "Fine-tuning vs RAG",
        "Hallucinations & Grounding",
        "LLM Tool / Function Calling",
        "Streaming Responses",
        "AI Agents",
        "Gemini & OpenAI API Integration",
    ],
};
