export const jsInterviewQuestions = {
  basic: [
    "What is JavaScript?",
    "What are the different data types in JavaScript?",
    "What is the difference between null and undefined?",
    "What is the difference between let, const, and var?",
    "What is hoisting?",
    "What is scope in JavaScript?",
    "What are global, function, and block scopes?",
    "What are truthy and falsy values?",
    "What is type coercion?",
    "What is the difference between == and ===?",
    "What are template literals?",
    "What are arrow functions?",
    "What is the difference between function declaration and function expression?",
    "What is a callback function?",
    "What are arrays in JavaScript?",
    "What is the difference between map, filter, and reduce?",
    "How do push and pop work?",
    "How do shift and unshift work?",
    "What is destructuring?",
    "What is the spread operator (...)?",
    "What is the rest operator (...)?",
    "What are objects in JavaScript?",
    "How do you access object properties?",
    "What is optional chaining (?.)?",
    "What is nullish coalescing (??)?"
  ],

  intermediate: [
    "What is a closure?",
    "What is lexical scope?",
    "What is the this keyword?",
    "How does this behave in arrow functions?",
    "What are higher-order functions?",
    "What is the difference between map and forEach?",
    "What is the event loop?",
    "What is the call stack?",
    "What are microtasks and macrotasks?",
    "What is asynchronous programming?",
    "What are Promises?",
    "What are Promise states?",
    "What is async/await?",
    "How does Promise.all work?",
    "What is Promise.race?",
    "What is Promise.allSettled?",
    "What is Promise.any?",
    "What is debouncing?",
    "What is throttling?",
    "What is event delegation?",
    "What is event bubbling?",
    "What is event capturing?",
    "What is DOM manipulation?",
    "What is the difference between innerHTML and textContent?",
    "What is localStorage?",
    "What is sessionStorage?",
    "What are cookies?",
    "What is JSON?",
    "What is JSON.stringify()?",
    "What is JSON.parse()?"
  ],

  advanced: [
    "What is the prototype chain?",
    "How does prototypal inheritance work?",
    "What is the difference between __proto__ and prototype?",
    "How does the new keyword work?",
    "What are constructor functions?",
    "What are ES6 classes?",
    "What is inheritance in JavaScript?",
    "What are static methods?",
    "What are getters and setters?",
    "What are private class fields?",
    "What are generators?",
    "What is the yield keyword?",
    "What are iterators?",
    "What are symbols?",
    "What is a WeakMap?",
    "What is a WeakSet?",
    "What is currying?",
    "What is function composition?",
    "What is memoization?",
    "What is a pure function?",
    "What are side effects?",
    "What is immutability?",
    "What is the difference between shallow copy and deep copy?",
    "How can you deep clone an object?",
    "What is Object.freeze()?",
    "What is Object.seal()?",
    "What is Object.create()?",
    "What is the Temporal Dead Zone (TDZ)?",
    "What are modules in JavaScript?",
    "What is the difference between CommonJS and ES Modules?"
  ],

  expert: [
    "Explain the JavaScript execution context.",
    "How does the JavaScript engine work?",
    "Explain memory allocation and garbage collection.",
    "What is mark-and-sweep garbage collection?",
    "What are memory leaks and how do you prevent them?",
    "Explain the event loop with code examples.",
    "Predict the output of complex async code.",
    "How do microtasks execute before macrotasks?",
    "Implement your own Promise.",
    "Implement call, apply, and bind.",
    "Implement debounce from scratch.",
    "Implement throttle from scratch.",
    "Implement map, filter, and reduce polyfills.",
    "Implement a deep clone function.",
    "Explain V8 engine optimizations.",
    "What is tree shaking?",
    "What is code splitting?",
    "How do JavaScript modules work internally?",
    "Explain execution order of async/await.",
    "What are Web Workers?",
    "What is the difference between concurrency and parallelism?",
    "How does the browser render a webpage?",
    "Explain the Critical Rendering Path.",
    "How do closures affect memory usage?",
    "How would you optimize JavaScript performance?"
  ],
  mustKnow: [
    "let vs const vs var",
    "Hoisting",
    "Closures",
    "Scope",
    "this keyword",
    "Arrow Functions",
    "Promises",
    "Async/Await",
    "Event Loop",
    "Call Stack",
    "Microtask vs Macrotask",
    "Map vs Filter vs Reduce",
    "Debounce vs Throttle",
    "Event Delegation",
    "Prototype & Inheritance",
    "Shallow vs Deep Copy",
    "Currying",
    "Memoization",
    "Promise.all vs Promise.allSettled",
    "Execution Context"
  ]
};
