export const nextjsInterviewQuestions = {
  basic: [
    "What is Next.js?",
    "Why use Next.js instead of React?",
    "What are the main features of Next.js?",
    "How do you create a Next.js application?",
    "What is file-based routing?",
    "How does routing work in Next.js?",
    "What is the App Router?",
    "What is the Pages Router?",
    "What is the difference between App Router and Pages Router?",
    "What are layouts in Next.js?",
    "What are nested layouts?",
    "What is a page in Next.js?",
    "What is the Link component?",
    "Why use Link instead of anchor tags?",
    "What is Image optimization in Next.js?",
    "What is the Image component?",
    "What is metadata in Next.js?",
    "How do you add SEO tags in Next.js?",
    "What are dynamic routes?",
    "What are route parameters?",
    "What is the public folder?",
    "How do static assets work in Next.js?",
    "What are environment variables in Next.js?",
    "How do you use .env files?",
    "How do you deploy a Next.js application?"
  ],

  intermediate: [
    "What is Server-Side Rendering (SSR)?",
    "What is Static Site Generation (SSG)?",
    "What is Incremental Static Regeneration (ISR)?",
    "What is Client-Side Rendering (CSR)?",
    "What is the difference between SSR, SSG, ISR, and CSR?",
    "What are Server Components?",
    "What are Client Components?",
    "How do you create a Client Component?",
    "What does 'use client' do?",
    "When should you use Server Components?",
    "When should you use Client Components?",
    "What are loading.js files?",
    "What are error.js files?",
    "What are not-found.js files?",
    "What is middleware in Next.js?",
    "How does middleware work?",
    "What are route handlers?",
    "How do API routes work?",
    "What is the fetch API in Next.js?",
    "How does data fetching work in App Router?",
    "What is generateMetadata()?",
    "What is generateStaticParams()?",
    "What is revalidation?",
    "How do caching strategies work in Next.js?",
    "How do redirects work in Next.js?",
    "How do rewrites work in Next.js?",
    "What are dynamic imports?",
    "What is lazy loading?",
    "How do you optimize images in Next.js?",
    "How do you optimize fonts in Next.js?"
  ],

  advanced: [
    "How does Next.js rendering work internally?",
    "How does React Server Components work in Next.js?",
    "What is streaming in Next.js?",
    "How does Suspense work with streaming?",
    "What is Partial Prerendering (PPR)?",
    "How does caching work in Next.js?",
    "What are request memoization and data cache?",
    "What is Full Route Cache?",
    "What is Router Cache?",
    "How does revalidatePath() work?",
    "How does revalidateTag() work?",
    "What are server actions?",
    "How do server actions work?",
    "What are edge functions?",
    "What is the Edge Runtime?",
    "Node.js Runtime vs Edge Runtime?",
    "How does middleware execute at the edge?",
    "How does authentication work in Next.js?",
    "How do you implement protected routes?",
    "How do you handle JWT authentication?",
    "How do you handle session authentication?",
    "How does NextAuth/Auth.js work?",
    "How do you implement role-based access control?",
    "How do you handle API security in Next.js?",
    "How do you optimize Core Web Vitals?",
    "How do you reduce bundle size?",
    "How do you debug hydration errors?",
    "What causes hydration mismatch errors?",
    "How do you optimize large Next.js applications?",
    "How would you structure a scalable Next.js project?"
  ],

  expert: [
    "Explain the complete Next.js request lifecycle.",
    "How does Next.js decide between static and dynamic rendering?",
    "Explain the internal architecture of App Router.",
    "How does React Flight work?",
    "How are Server Components serialized and sent to the browser?",
    "How does streaming improve performance?",
    "How does cache invalidation work in Next.js?",
    "How would you implement a custom caching strategy?",
    "How do server actions eliminate API routes?",
    "How would you build a multi-tenant SaaS application in Next.js?",
    "How would you implement internationalization (i18n)?",
    "How would you implement micro-frontends with Next.js?",
    "How would you optimize a Next.js app with millions of users?",
    "How would you handle distributed authentication?",
    "How would you secure Server Actions?",
    "How would you implement rate limiting?",
    "How would you implement feature flags?",
    "How would you design a scalable folder structure?",
    "How would you monitor performance in production?",
    "How would you handle large file uploads?",
    "How would you implement real-time updates?",
    "How would you integrate WebSockets in Next.js?",
    "How would you implement server-side caching with Redis?",
    "How would you troubleshoot memory leaks in Next.js?",
    "How would you optimize TTFB and LCP?"
  ],

  practicalCoding: [
    "Create a dynamic route page.",
    "Build a blog using App Router.",
    "Implement SSR data fetching.",
    "Implement SSG pages.",
    "Implement ISR with revalidation.",
    "Build a protected dashboard.",
    "Implement login/logout using JWT.",
    "Implement Auth.js authentication.",
    "Create API route CRUD operations.",
    "Create route handlers.",
    "Build a server action form.",
    "Implement file upload functionality.",
    "Implement pagination.",
    "Implement search functionality.",
    "Implement infinite scrolling.",
    "Implement role-based access control.",
    "Create middleware-based authentication.",
    "Implement dark/light theme.",
    "Optimize a slow Next.js page.",
    "Fix hydration mismatch errors."
  ],
  MustKnow: [
    "What is Next.js?",
    "App Router vs Pages Router",
    "SSR vs SSG vs ISR vs CSR",
    "Server Components vs Client Components",
    "'use client' directive",
    "File-based routing",
    "Dynamic routes",
    "Layouts and Nested Layouts",
    "Loading.js and Error.js",
    "Route Handlers",
    "Middleware",
    "Server Actions",
    "Data Fetching in App Router",
    "Caching and Revalidation",
    "revalidatePath vs revalidateTag",
    "Authentication in Next.js",
    "JWT vs Session Authentication",
    "NextAuth/Auth.js",
    "Image Optimization",
    "SEO and Metadata",
    "Streaming and Suspense",
    "Hydration Errors",
    "Edge Runtime vs Node Runtime",
    "Performance Optimization",
    "Deployment and Production Best Practices"
  ]
};