export const nodeExpressInterviewQuestions = {
    basic: [
        "What is Node.js?",
        "Is Node.js a programming language?",
        "What is the V8 Engine?",
        "How does Node.js work?",
        "Why is Node.js single-threaded?",
        "What is the Event Loop?",
        "What are the phases of the Event Loop?",
        "What is non-blocking I/O?",
        "What is asynchronous programming?",
        "What is the difference between synchronous and asynchronous code?",
        "What is npm?",
        "What is package.json?",
        "What is package-lock.json?",
        "What is npx?",
        "What are CommonJS modules?",
        "What are ES Modules?",
        "What is require()?",
        "What is import/export?",
        "What are environment variables?",
        "How do you use dotenv?",
        "What is Express.js?",
        "Why use Express.js?",
        "How do you create an Express server?",
        "What is middleware?",
        "What is the request object (req)?",
        "What is the response object (res)?",
        "What is routing in Express?",
        "How do route parameters work?",
        "What is express.json()?",
        "What is express.urlencoded()?"
    ],

    intermediate: [
        "What is custom middleware?",
        "How does middleware execution order work?",
        "What is next() in Express?",
        "What is error handling middleware?",
        "How do you handle errors globally?",
        "What are HTTP methods?",
        "What is REST API?",
        "What is RESTful API design?",
        "What are HTTP status codes?",
        "Difference between PUT and PATCH?",
        "Difference between authentication and authorization?",
        "What is JWT?",
        "How does JWT authentication work?",
        "What are refresh tokens?",
        "How do cookies work?",
        "What is CORS?",
        "How do you enable CORS in Express?",
        "What is Helmet?",
        "How do you secure Express applications?",
        "What is bcrypt?",
        "Why hash passwords?",
        "What are streams in Node.js?",
        "What are buffers in Node.js?",
        "What is EventEmitter?",
        "What are child processes?",
        "What is clustering?",
        "What is rate limiting?",
        "How do file uploads work in Express?",
        "How do you structure a Node.js project?",
        "How do you connect Node.js with MongoDB?"
    ],

    advanced: [
        "How does the Event Loop work internally?",
        "What are microtasks and macrotasks in Node.js?",
        "process.nextTick() vs setImmediate()?",
        "What is libuv?",
        "How does Node.js achieve concurrency?",
        "What is the Thread Pool?",
        "How do Worker Threads work?",
        "What are streams and their types?",
        "Readable vs Writable vs Duplex vs Transform streams?",
        "How does backpressure work in streams?",
        "How do you implement authentication middleware?",
        "How do you implement role-based authorization?",
        "How do you secure JWT tokens?",
        "How do you handle API versioning?",
        "How do you implement pagination?",
        "How do you implement search and filtering?",
        "How do you optimize Express performance?",
        "How do you cache API responses?",
        "What is Redis and why is it used?",
        "How do you implement Redis caching?",
        "How do you implement logging?",
        "What is Morgan?",
        "How do you implement centralized error handling?",
        "How do you handle large file uploads?",
        "How do you implement WebSockets?",
        "How do you implement Socket.IO?",
        "How do you handle database transactions?",
        "How do you prevent memory leaks?",
        "How do you scale Node.js applications?",
        "How do you deploy Node.js applications?"
    ],

    expert: [
        "Explain Node.js architecture in detail.",
        "Explain the complete request lifecycle in Node.js.",
        "How does Express handle requests internally?",
        "How does middleware chaining work internally?",
        "Explain the Event Loop with execution examples.",
        "Predict the output of complex Event Loop code.",
        "How does Node.js handle thousands of concurrent requests?",
        "How would you build your own Express-like framework?",
        "How would you implement JWT authentication from scratch?",
        "How would you implement rate limiting?",
        "How would you build a scalable REST API?",
        "How would you build a microservices architecture?",
        "Monolith vs Microservices?",
        "How would you implement API Gateway?",
        "How would you implement distributed caching?",
        "How would you handle millions of requests per day?",
        "How would you implement queue systems?",
        "How do RabbitMQ and Kafka work?",
        "How would you implement background jobs?",
        "How would you optimize database performance?",
        "How would you secure a production Node.js application?",
        "How would you handle horizontal scaling?",
        "How would you monitor Node.js applications?",
        "How would you troubleshoot high CPU usage?",
        "How would you troubleshoot memory leaks?"
    ],

    practicalCoding: [
        "Build a CRUD REST API.",
        "Implement JWT authentication.",
        "Implement Refresh Tokens.",
        "Create Authentication Middleware.",
        "Create Authorization Middleware.",
        "Implement Role-Based Access Control (RBAC).",
        "Build a User Login/Register API.",
        "Implement Password Reset API.",
        "Implement File Upload API using Multer.",
        "Implement Pagination API.",
        "Implement Search and Filter API.",
        "Implement Global Error Handler.",
        "Implement API Rate Limiting.",
        "Implement Redis Caching.",
        "Build a URL Shortener API.",
        "Build a Blog API.",
        "Build an E-commerce Backend.",
        "Implement Socket.IO Chat App.",
        "Build Notification System.",
        "Implement Email Sending Service.",
        "Implement Queue Jobs using BullMQ.",
        "Implement API Logging.",
        "Implement Request Validation using Joi/Zod.",
        "Optimize a Slow API Endpoint.",
        "Design a Production-Ready Backend Structure."
    ],
    mustKnow: [
        "What is Node.js?",
        "Event Loop",
        "Single Threaded Architecture",
        "Asynchronous Programming",
        "Promises and Async/Await",
        "process.nextTick vs setImmediate",
        "Streams",
        "Buffers",
        "EventEmitter",
        "Express Middleware",
        "Request Lifecycle",
        "REST API Design",
        "JWT Authentication",
        "Authentication vs Authorization",
        "Refresh Tokens",
        "CORS",
        "bcrypt",
        "Error Handling",
        "Rate Limiting",
        "File Uploads",
        "Redis Caching",
        "WebSockets / Socket.IO",
        "Project Structure",
        "API Security",
        "Performance Optimization"
    ],
};