export const pythonInterviewQuestions = {
    basic: [
        "What is Python?",
        "Why is Python popular?",
        "Is Python compiled or interpreted?",
        "What are Python data types?",
        "What is a variable in Python?",
        "How do you take input from the user?",
        "How do you print output in Python?",
        "What are keywords in Python?",
        "What is indentation in Python and why is it important?",
        "What is type conversion in Python?",
        "What is the difference between list, tuple, set, and dictionary?",
        "What are mutable and immutable types?",
        "What are operators in Python?",
        "What are if-else statements?",
        "What are loops in Python?",
        "What is a for loop?",
        "What is a while loop?",
        "What is the difference between break and continue?",
        "What are functions in Python?",
        "How do you define a function?",
        "What is return in a function?",
        "What is a default argument?",
        "What are *args and **kwargs (basic idea)?",
        "What is a module in Python?",
        "How do you import a module?"
    ],

    intermediate: [
        "What is list comprehension?",
        "What is slicing in Python?",
        "What is exception handling?",
        "What is try, except, finally?",
        "What is file handling in Python?",
        "How do you read a file?",
        "How do you write to a file?",
        "What is OOP in Python?",
        "What is a class?",
        "What is an object?",
        "What is __init__ method?",
        "What is self in Python?",
        "What is inheritance?",
        "What is polymorphism?",
        "What is encapsulation?",
        "What is abstraction?",
        "What is method overloading (basic idea)?",
        "What is method overriding?",
        "What are Python libraries?",
        "What is pip?"
    ],

    codingPractice: [
        "Write a program to check even or odd number",
        "Write a program to find factorial of a number",
        "Write a program to find Fibonacci series",
        "Write a program to reverse a string",
        "Write a program to check palindrome",
        "Write a program to find largest number in a list",
        "Write a program to remove duplicates from a list",
        "Write a program to count vowels in a string",
        "Write a simple calculator program",
        "Write a program to sort a list"
    ],
    MustKnow: [
        "Variables and Data Types",
        "Lists, Tuples, Sets, Dictionaries",
        "If-Else Conditions",
        "Loops (for, while)",
        "Functions",
        "Basic OOP (Class & Object)",
        "File Handling Basics",
        "Exception Handling",
        "Input/Output",
        "Basic String Operations"
    ]
};