export const reactInterviewQuestions = {
  basic: [
    "What is React?",
    "Why is React popular?",
    "What are the main features of React?",
    "What is JSX?",
    "How does JSX work?",
    "What is the Virtual DOM?",
    "What is the difference between DOM and Virtual DOM?",
    "What are React components?",
    "What is the difference between Functional and Class Components?",
    "What are Props in React?",
    "What is State in React?",
    "What is the difference between Props and State?",
    "What is one-way data binding?",
    "What is React Fragment?",
    "Why do we use keys in React lists?",
    "What happens if keys are not unique?",
    "What are controlled components?",
    "What are uncontrolled components?",
    "How do you handle events in React?",
    "What is conditional rendering?",
    "How do you render lists in React?",
    "What is React.StrictMode?",
    "What is ReactDOM?",
    "What is the purpose of the root element?",
    "How do you create a React application?"
  ],

  intermediate: [
    "What is useState?",
    "What is useEffect?",
    "When does useEffect run?",
    "What is the dependency array in useEffect?",
    "What is useRef?",
    "What is useMemo?",
    "What is useCallback?",
    "What is React.memo?",
    "What is useContext?",
    "What is Context API?",
    "How does Context API work?",
    "What is prop drilling?",
    "How can you avoid prop drilling?",
    "What is component lifecycle?",
    "How do lifecycle methods map to Hooks?",
    "What is lifting state up?",
    "What are custom hooks?",
    "How do you create a custom hook?",
    "What is useReducer?",
    "When should you use useReducer instead of useState?",
    "What is lazy loading in React?",
    "What is React.lazy?",
    "What is Suspense?",
    "What is code splitting?",
    "How do forms work in React?",
    "How do you handle form validation?",
    "What is forwardRef?",
    "What is useImperativeHandle?",
    "What is reconciliation?",
    "How does React update the UI?"
  ],

  advanced: [
    "What is the React Fiber architecture?",
    "How does React reconciliation work internally?",
    "How does React diffing algorithm work?",
    "What causes a component to re-render?",
    "How can you prevent unnecessary re-renders?",
    "How does React.memo work internally?",
    "What is memoization in React?",
    "When should you use useMemo?",
    "When should you use useCallback?",
    "What are Higher Order Components (HOC)?",
    "What are Render Props?",
    "What is the difference between HOC and Hooks?",
    "What is server-side rendering (SSR)?",
    "What is client-side rendering (CSR)?",
    "What is static site generation (SSG)?",
    "What is hydration in React?",
    "What are React Portals?",
    "Why are Portals used?",
    "What are Error Boundaries?",
    "How do Error Boundaries work?",
    "What is Concurrent Rendering?",
    "What is React Suspense for data fetching?",
    "What is automatic batching in React 18?",
    "What is Strict Mode's double rendering behavior?",
    "What are synthetic events?",
    "What is React's event delegation system?",
    "How do you optimize React applications?",
    "What is tree shaking in React projects?",
    "How do you manage global state in React?",
    "Redux vs Context API?"
  ],

  expert: [
    "Explain React rendering from state update to DOM update.",
    "Explain React Fiber in detail.",
    "How does React schedule updates?",
    "What are React lanes?",
    "How does Concurrent Mode work?",
    "How does React batching work internally?",
    "What happens when setState is called?",
    "Why is state update asynchronous?",
    "How would you build your own useState hook?",
    "How would you build your own useEffect hook?",
    "How would you implement React.memo from scratch?",
    "How does React compare dependency arrays?",
    "What are stale closures in React?",
    "How do you prevent stale state issues?",
    "Explain React hydration mismatches.",
    "How do you debug React performance issues?",
    "How do you profile React applications?",
    "What is bundle optimization in React?",
    "How do you implement authentication in React?",
    "How do you handle role-based authorization?",
    "How would you structure a large-scale React application?",
    "How do you handle API caching in React?",
    "How does React Query work?",
    "What are optimistic updates?",
    "How do you implement infinite scrolling?",
    "How do you implement virtualized lists?",
    "How do you secure a React application?",
    "How do you manage application state at scale?",
    "How would you design a reusable component library?",
    "What are the most common React performance bottlenecks?"
  ],

  practicalCoding: [
    "Create a Counter using useState.",
    "Create a Todo App.",
    "Implement Debounced Search.",
    "Build a Custom useDebounce Hook.",
    "Build a Custom useLocalStorage Hook.",
    "Implement Infinite Scroll.",
    "Create a Modal using React Portal.",
    "Build a Multi-Step Form.",
    "Create Dark/Light Theme using Context API.",
    "Implement Protected Routes.",
    "Fetch API Data using useEffect.",
    "Create Pagination Component.",
    "Create Reusable Table Component.",
    "Create Reusable Input Component.",
    "Implement Search and Filter Functionality.",
    "Optimize a Slow React Component.",
    "Build a Custom useFetch Hook.",
    "Build a Custom usePrevious Hook.",
    "Implement Drag and Drop List.",
    "Create a File Upload Component."
  ],
  MustKnow: [
    "JSX",
    "Virtual DOM",
    "Props vs State",
    "useState",
    "useEffect",
    "Dependency Array",
    "useRef",
    "useMemo vs useCallback",
    "React.memo",
    "Context API",
    "Prop Drilling",
    "Lifting State Up",
    "Re-rendering in React",
    "Conditional Rendering",
    "Keys in Lists",
    "React Lifecycle (Hooks mapping)",
    "Custom Hooks",
    "React Router",
    "Code Splitting / Lazy Loading",
    "Performance Optimization",
    "https://jsdev.space/react-interview-questions-2026/?ref=dailydev"
  ],
};