export const typescriptInterviewQuestions = {
    basic: [
        "What is TypeScript and how does it differ from JavaScript?",
        "What are the main benefits of using TypeScript?",
        "How do you install and configure TypeScript in a project?",
        "What is tsconfig.json and what does it do?",
        "What are primitive types in TypeScript? (string, number, boolean)",
        "What is the 'any' type and when should you avoid it?",
        "What is the 'void' type?",
        "What is the 'never' type?",
        "What is 'null' vs 'undefined' in TypeScript?",
        "What is type inference?",
        "How do you declare a variable with a specific type?",
        "What is an interface in TypeScript?",
        "How do you define optional properties in an interface?",
        "What is a readonly property?",
        "What is an enum in TypeScript?",
        "What is the difference between string enums and numeric enums?",
        "What are arrays and tuples in TypeScript?",
        "What is a union type?",
        "What is an intersection type?",
        "What is type aliasing with 'type'?",
    ],

    intermediate: [
        "What is the difference between 'interface' and 'type'?",
        "What are Generics in TypeScript?",
        "How do you use Generics with functions?",
        "How do you use Generics with interfaces?",
        "What are Utility Types? Explain Partial, Required, Pick, Omit, Readonly.",
        "What are discriminated unions?",
        "Explain 'unknown' vs 'any' — when to use each.",
        "What are mapped types?",
        "What are conditional types?",
        "What are type guards? How do you use 'typeof' and 'instanceof'?",
        "What is a type assertion?",
        "What is the 'satisfies' operator in TypeScript?",
        "What are index signatures?",
        "What is declaration merging?",
        "What are namespaces in TypeScript?",
        "What is the 'keyof' operator?",
        "What is the 'typeof' operator in types?",
        "What are template literal types?",
        "How does TypeScript handle function overloading?",
        "What are decorators in TypeScript?",
    ],

    advanced: [
        "What are infer types in conditional types?",
        "What are recursive types?",
        "Explain the Exclude, Extract, NonNullable, ReturnType, InstanceType utility types.",
        "What are variadic tuple types?",
        "How do you type a REST API response in TypeScript?",
        "How do you type environment variables in a Next.js project?",
        "What is 'strict' mode in TypeScript and what does it enable?",
        "How do you create a type-safe event emitter?",
        "What are module augmentation and declaration merging?",
        "How do you handle third-party libraries with no type definitions?",
    ],

    practical: [
        "Type a function that accepts any object and returns a specific key's value.",
        "Create a generic function to filter an array.",
        "Create a type-safe API response wrapper.",
        "Type a React component's props using an interface.",
        "Use Partial<T> to make all fields optional for an update operation.",
        "Use Pick<T> to select only needed fields from a large interface.",
        "Create a discriminated union for different notification types.",
        "Use generics to build a reusable fetch utility with typed response.",
        "Create a mapped type to make all properties nullable.",
        "Type a Redux-like reducer using discriminated unions.",
    ],

    MustKnow: [
        "Generics",
        "Type vs Interface",
        "Utility Types (Partial, Pick, Omit, Readonly)",
        "Union & Intersection Types",
        "Type Guards",
        "Discriminated Unions",
        "Mapped Types",
        "keyof & typeof Operators",
        "strict Mode",
        "Typing React Props & API Responses",
    ],
};
