export const web3InterviewQuestions = {
    basic: [
        "What is Web3?",
        "How is Web3 different from Web2?",
        "What is blockchain?",
        "What is decentralization?",
        "What is a cryptocurrency?",
        "What is Ethereum?",
        "What is a smart contract?",
        "What is gas fee in blockchain?",
        "What is a wallet in Web3?",
        "What is MetaMask?",
        "What is a transaction in blockchain?",
        "What is a block?",
        "What is hashing in blockchain?",
        "What is a public and private key?",
        "What is a decentralized application (dApp)?"
    ],

    intermediate: [
        "How do smart contracts work?",
        "What is Solidity?",
        "What is ERC-20 token standard?",
        "What is ERC-721 (NFT standard)?",
        "What is ERC-1155?",
        "What is tokenization?",
        "What is gas limit vs gas price?",
        "How do transactions get confirmed?",
        "What is mining?",
        "What is staking?",
        "What is Proof of Work (PoW)?",
        "What is Proof of Stake (PoS)?",
        "What is a node in blockchain?",
        "What is a distributed ledger?",
        "What is Web3.js or Ethers.js?",
        "How does a dApp connect to blockchain?",
        "What is IPFS?",
        "What is an NFT?",
        "How do NFT marketplaces work?",
        "What is event logging in smart contracts?"
    ],

    advanced: [
        "How do smart contracts get deployed?",
        "What is ABI in smart contracts?",
        "What is bytecode?",
        "How does Ethereum Virtual Machine (EVM) work?",
        "What is contract inheritance in Solidity?",
        "What are modifiers in Solidity?",
        "What are view and pure functions?",
        "What is reentrancy attack?",
        "How do you prevent reentrancy?",
        "What are security vulnerabilities in smart contracts?",
        "What is front-running in blockchain?",
        "What is MEV (Maximal Extractable Value)?",
        "How does Layer 2 scaling work?",
        "What is rollups (Optimistic vs ZK)?",
        "What is sharding?",
        "What is cross-chain communication?",
        "How does Web3 authentication work?",
        "How do wallets sign transactions?",
        "How does gas optimization work?",
        "How do decentralized exchanges (DEX) work?"
    ],

    practicalCoding: [
        "Write a simple smart contract in Solidity",
        "Create a token using ERC-20 standard",
        "Create an NFT using ERC-721",
        "Connect React app with MetaMask",
        "Fetch blockchain data using Ethers.js",
        "Send a transaction using Web3.js",
        "Deploy smart contract using Hardhat",
        "Write a contract with ownership control",
        "Implement a voting smart contract",
        "Build a simple dApp frontend"
    ],
    MustKnow: [
        "Blockchain basics",
        "Smart contracts",
        "Ethereum ecosystem",
        "Gas fees",
        "Wallets (MetaMask)",
        "ERC-20 / ERC-721",
        "Web3.js / Ethers.js",
        "dApp architecture",
        "Transactions lifecycle",
        "Public / Private keys",
        "Security issues (reentrancy)",
        "Proof of Work vs Proof of Stake",
        "NFT basics",
        "Smart contract deployment",
        "Frontend + blockchain integration"
    ]
};